# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmify < Formula
  desc "Creates Helm chart from Kubernetes yaml."
  homepage "https://github.com/arttor/helmify"
  version "0.4.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arttor/helmify/releases/download/v0.4.10/helmify_Darwin_arm64.tar.gz"
      sha256 "725c9d339c183cbb8ef80a93e9b1a04f54ab3f52b783dea2c479c9b5aa1314e5"

      def install
        bin.install "helmify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arttor/helmify/releases/download/v0.4.10/helmify_Darwin_x86_64.tar.gz"
      sha256 "1888823d55ab914ba8c04f02af191a0444156c58a0fc9e96ff24837bdb65a1cb"

      def install
        bin.install "helmify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arttor/helmify/releases/download/v0.4.10/helmify_Linux_x86_64.tar.gz"
      sha256 "e80d9134e0566b027bab3c791f1e32147132d4c92c8daf012b91bdfead6e6b30"

      def install
        bin.install "helmify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arttor/helmify/releases/download/v0.4.10/helmify_Linux_arm64.tar.gz"
      sha256 "43e6eb6332e946bd0f0c08b89f171ff25203de2f8f0524123663d0c796d62b41"

      def install
        bin.install "helmify"
      end
    end
  end

  test do
    system "#{bin}/helmify --version"
  end
end
